### ISSUE TITLE
Can the app be published to the MacOS App Store?

### ISSUE THREAD

**Issue by Andrew-web-coder** [amrbashir/tauri-plugin-vibrancy#118]
Hello,

I am considering moving from Electron to Tauri, but the problem is that I really need transparent windows and I saw this warning:

```
WARNING: Using private APIs on macOS prevents your application from being accepted to the App Store.
```

Is it true that Apple will reject my app for this reason? That would be a deal breaker :(

**Comment by FabianLars** [comment]
To our knowledge yes. But i'm not sure if somebody actually tried it (with a transparent tauri app).

**Comment by Andrew-web-coder** [comment]
Well, I was hoping someone with actual experience would confirm or deny this :/  I'll stick with Electron until I'm confident I can migrate and publish my app to the App Store.

**Comment by scris** [comment]
I'm curious about why Electron can avoid using such private APIs while Tauri can't. Can anyone explain that? Thanks a lot!

**Comment by FabianLars** [comment]
Because electron uses chromium directly and we use the system webview as the renderer (wkwebview). For some reason, wkwebview does not have a supported way to make it transparent (on macos) so we have to use a private api for that.

As far as i know this private api in particular doesn't seem to cause issues when submitting the app. or at least not for everyone since a few community members told me it was fine for them 🤷

**Comment by scris** [comment]
Thanks for your clarification! :)
