### ISSUE TITLE
Dark Mode override

### ISSUE THREAD

**Issue by austenc** [amrbashir/tauri-plugin-vibrancy#86]
Thank you for creating this plugin, it works great for macOS in my uses so far!

Wondering if it's possible to manually set the appearance to dark or light based on an application setting (not just the system setting)?

The use case would be a dark mode toggle in an app that allows the user to override and/or differ from the system. Is this something that can be exposed to Rust via this plugin? 

If not, I'll gladly close this. Thank you!

**Comment by amrbashir** [comment]
I am not a macOS developer so I am not sure if this is possible, but you could try calling `apply_vibrancy` with the variant you need, and see if it changes it, if not, then you probably need to save the toggle value onto disk and request your users to restart the app, where it will re-read the saved toggle value and applies the appropriate effect.

**Comment by lorenzolewis** [comment]
I did a bit of quick digging on this. It does appear that Electron had this option at one point (https://github.com/electron/electron/pull/7898) that used values such as NSVisualEffectMaterialAppearanceBased, NSVisualEffectMaterialLight and NSVisualEffectMaterialDark. However those have since been [deprecated as of macOS 10.14](https://developer.apple.com/documentation/appkit/nsvisualeffectview/material/light). What I didn't see was a way to specify this for macOS 10.15 and greater. Here's the overall page for NSVisualEffectView: https://developer.apple.com/documentation/appkit/nsvisualeffectview 

To be honest I wouldn't be surprised if this is no longer "officially" possible/supported in macOS to change the vibrancy of a window independently from the global OS colour scheme (but I could be wrong on this).

**Comment by austenc** [comment]
Amr and Lorenzo, 

Thank you both for your responses! Yeah, clearly those light/dark materials are deprecated when looking at the macOS docs. 
I think my "need" for this was based on experience developing websites, not desktop apps. In the desktop app realm it seems that the system setting controls the application's look and feel in most cases. 

Given that, happily closing this issue -- the plugin works great with that case already. People needing a manual toggle will need to create another workaround. 

Thank you for looking at it!

**Comment by austenc** [comment]
I just encountered this again and to my surprise I found this issue when googling. If you have a manual dark mode toggle (options are `dark`, `light`, and `system`) in your application _and you enable vibrancy_ it leads to some strange behavior. 

For example, the user sets the in-app setting to `dark` but their system setting is on _light_ mode -- there is no way (that I can tell) to get the vibrancy setting to differ from the system for the application. 

My workaround/solution is going to be forcing `system` setting (and not providing a dark mode toggle) when vibrancy is enabled. Either:

- Vibrancy is disabled, user can select one of the three theme options
- Vibrancy is enabled, user setting is forced to `system` and there is no toggle. 

Hopefully that helps anyone else who might run into this.
